{
 "title": "Cserve",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "GPU Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "endpoint:gpu_cache_usage_perc", "legendFormat": "__auto" },
    {
     "expr": "endpoint:gpu_prefix_cache_hit_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CServe Token Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "endpoint:avg_generation_throughput_toks_per_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "endpoint:avg_prompt_throughput_toks_per_s",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CServe Tokens Generated",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint:generation_tokens_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Prompt Tokens",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endpoint:prompt_tokens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "endpoint:request_prompt_tokens_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}